# Generated by Django 2.2.14 on 2020-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='web_site',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
