# Generated by Django 2.2.14 on 2020-08-04 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='nombre')),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='teach_thumbnails')),
                ('image', models.ImageField(blank=True, default='', upload_to='teach_images')),
                ('text', models.TextField(verbose_name='texto')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
