# Generated by Django 2.2.14 on 2020-08-05 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tags',
            field=models.ManyToManyField(blank=True, to='teachers.Tag'),
        ),
    ]
